export const GET_STORIES = "GET_STORIES";
export const FETCH_STORIES_REQUEST = "FETCH_STORIES_REQUEST";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const FETCH_STORIES_ERROR = "FETCH_STORIES_ERROR";